using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimLE;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeneralStores = Mutagen.Bethesda.FormKeys.SkyrimSE.GeneralStores;

namespace GeneralStoresIngredientsPatcher
{
    public class Program
    {
        static Lazy<Settings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "GeneralStoresIngredientsPatcher.esp")
                .Run(args);
        }

        public static readonly HashSet<IFormLink<IKeywordGetter>> workbenchFilter = new(){
            Skyrim.Keyword.CraftingSmelter,
            Skyrim.Keyword.CraftingSmithingForge,
            Skyrim.Keyword.CraftingCookpot,
            Skyrim.Keyword.CraftingTanningRack,
            Skyrim.Keyword.isGrainMill,
            HearthFires.Keyword.BYOHCraftingOven,
            HearthFires.Keyword.BYOHCarpenterTable
        };

        public static readonly HashSet<IFormLink<IKeywordGetter>> workbenchesThatNeedNoItems = new(){
            Skyrim.Keyword.CraftingCookpot,
            Skyrim.Keyword.isGrainMill,
            HearthFires.Keyword.BYOHCraftingOven
        };

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var doNotUnburdenFormKeys = Settings.Value.DoNotUnburdenList;

            var allSmithingSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var smeltingSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var smithingSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var tanningSet = new HashSet<IFormLinkGetter<IItemGetter>>();

            var hearthFiresConstructionSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var hearthFiresIngredientSet = new HashSet<IFormLinkGetter<IItemGetter>>();

            var alchemyAndCookingSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var alchemyAndSmithingSet = new HashSet<IFormLinkGetter<IItemGetter>>();

            // VendorItemFoodRaw / VendorItemFood
            var allFoodSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var cookedFoodSet = new HashSet<IFormLinkGetter<IItemGetter>>();
            var rawFoodSet = new HashSet<IFormLinkGetter<IItemGetter>>();

            // gets set to different sets dependin on recipe type.
            var specificSet = allSmithingSet;
            var allSet = smeltingSet;
            var ingredientSet = alchemyAndSmithingSet;

            var formListsForWorkbench = new Dictionary<IFormLink<IKeywordGetter>, Action<IConstructibleObjectGetter>>()
            {
                {Skyrim.Keyword.CraftingSmelter, delegate {
                    ingredientSet = alchemyAndSmithingSet;
                    allSet = allSmithingSet;
                    specificSet = smeltingSet;
                }},
                {Skyrim.Keyword.CraftingSmithingForge, delegate {
                    ingredientSet = alchemyAndSmithingSet;
                    allSet = allSmithingSet;
                    specificSet = smithingSet;
                }},
                {Skyrim.Keyword.CraftingTanningRack, delegate {
                    ingredientSet = alchemyAndSmithingSet;
                    allSet = allSmithingSet;
                    specificSet = tanningSet;
                }},
                {HearthFires.Keyword.BYOHCarpenterTable, delegate {
                    ingredientSet = hearthFiresIngredientSet;
                    allSet = allSmithingSet;
                    specificSet = hearthFiresConstructionSet;
                }},
                {Skyrim.Keyword.CraftingCookpot, delegate(IConstructibleObjectGetter cobj) {
                    if (cobj.CreatedObject is IFormLink<IItemGetter> result) {
                        allFoodSet.Add(result);
                        cookedFoodSet.Add(result);
                    }
                    ingredientSet = alchemyAndCookingSet;
                    allSet = allFoodSet;
                    specificSet = rawFoodSet;
                }},
                {Skyrim.Keyword.isGrainMill, delegate(IConstructibleObjectGetter cobj) {
                    if (cobj.CreatedObject is IFormLink<IItemGetter> result) {
                        rawFoodSet.Add(result);
                        cookedFoodSet.Add(result);
                    }
                    ingredientSet = alchemyAndCookingSet;
                    allSet = allFoodSet;
                    specificSet = rawFoodSet;
                }},
            };

            formListsForWorkbench[HearthFires.Keyword.BYOHCraftingOven] = formListsForWorkbench[Skyrim.Keyword.CraftingCookpot];

            Console.WriteLine("Finding ingredients and results that we don't want to be burdened with.");

            foreach (var cobj in state.LoadOrder.PriorityOrder.ConstructibleObject().WinningOverrides())
            {
                if (cobj.WorkbenchKeyword is not IFormLink<IKeywordGetter> workbenchKeywordFormKey) continue;

                if (!workbenchFilter.Contains(workbenchKeywordFormKey)) continue;

                var items = cobj.Items;
                if (items == null && !workbenchesThatNeedNoItems.Contains(workbenchKeywordFormKey)) continue;

                formListsForWorkbench[workbenchKeywordFormKey](cobj);

                if (items == null) continue;
                foreach (var item in items)
                {
                    var itemFormKey = item.Item.Item;
                    var shouldUnburden = true;
                    if (doNotUnburdenFormKeys.Contains(itemFormKey))
                        shouldUnburden = false;

                    if (!item.Item.Item.TryResolve(state.LinkCache, out var record)) continue;

                    switch (record) {
                        case IIngredientGetter ingredient:
                        case IIngestibleGetter ingestible:
                            ingredientSet.Add(itemFormKey);
                            shouldUnburden = false;
                            break;
                        case IArmorGetter armor:
                            if (armor.EditorID?.Contains("Ring Shank") == true)
                                shouldUnburden = true; // intermediate ingredient from Immersive Jewellery
                            else
                                shouldUnburden = false;
                            break;
                        case IWeaponGetter weapon:
                            shouldUnburden = false;
                            break;
                        default:
                            shouldUnburden = true;
                            break;
                    }

                    if (shouldUnburden)
                    {
                        allSet.Add(itemFormKey);
                        specificSet.Add(itemFormKey);
                    }
                }
            }

            Console.WriteLine("Adding found items to GeneralStores Form Lists...");

            var modCount = state.LoadOrder.PriorityOrder.Count();

            var modKeyToPriority = state.LoadOrder.PriorityOrder
                .Select((x, i) => (x.ModKey, i))
                .ToDictionary(x => x.ModKey, x => (uint)(modCount - x.i));

            IOrderedEnumerable<IFormLinkGetter<IItemGetter>> orderByPriorityAndID(ISet<IFormLinkGetter<IItemGetter>> formKeySet) => formKeySet.OrderBy(x => ((ulong)modKeyToPriority[x.FormKey.ModKey] << 24) | x.FormKey.ID);

            void applySetToFLST(FormLink<IFormListGetter> flstKey, ISet<IFormLinkGetter<IItemGetter>> set)
            {
                var flst = state.LinkCache.Resolve<IFormListGetter>(flstKey);
                if (flst is null) return;

                var flstEDID = flst.EditorID;

                var missingSet = new HashSet<IFormLinkGetter<IItemGetter>>(set.Count);

                Console.WriteLine($"Found {set.Count} records that should be in {flstEDID}");

                var items = flst.Items
                    .ToHashSet();

                foreach (var thing in flst.Items)
                    if (thing is IFormLink<IItemGetter> item)
                        if (!set.Remove(item))
                            missingSet.Add(item);

                if (missingSet.Count > 0)
                {
                    Console.WriteLine($"The following {missingSet.Count} records in {flstEDID} were not in the records we found:");
                    foreach (var item in orderByPriorityAndID(missingSet))
                        Console.WriteLine($"    {item}");
                }

                Console.WriteLine($"Found {set.Count} new records to add to {flstEDID}");

                if (set.Count == 0) return;

                var modifiedFlst = state.PatchMod.FormLists.GetOrAddAsOverride(flst);

                modifiedFlst.Items.AddRange(orderByPriorityAndID(set));
            }

            applySetToFLST(GeneralStores.FormList.xGSxAlchCookFLST, alchemyAndCookingSet);
            applySetToFLST(GeneralStores.FormList.xGSxAlchSmithFLST, alchemyAndSmithingSet);

            applySetToFLST(GeneralStores.FormList.xGSxFoodAllFLST, allFoodSet);
            applySetToFLST(GeneralStores.FormList.xGSxFoodCookedFLST, cookedFoodSet);
            applySetToFLST(GeneralStores.FormList.xGSxFoodRawFLST, rawFoodSet);

            applySetToFLST(GeneralStores.FormList.xGSxAllSmithFLST, allSmithingSet);
            applySetToFLST(GeneralStores.FormList.xGSxSmeltingFLST, smeltingSet);
            applySetToFLST(GeneralStores.FormList.xGSxSmithingFLST, smithingSet);
            applySetToFLST(GeneralStores.FormList.xGSxTanningFLST, tanningSet);

            // these FormLists have been merged into GeneralStores.esm in SkyrimSE/VR, but are in a separate plugin in SkyrimLE.
            switch (state.Settings.GameRelease)
            {
                case GameRelease.SkyrimSE:
                case GameRelease.SkyrimVR:
                    applySetToFLST(GeneralStores.FormList.xHFSxConstructionFLST, hearthFiresConstructionSet);
                    applySetToFLST(GeneralStores.FormList.xHFSxIngredientsFLST, hearthFiresIngredientSet);
                    break;
                case GameRelease.SkyrimLE:
                    if (state.LoadOrder.PriorityOrder.HasMod(HearthFireStores_GS.FormList.xHFSxConstructionFLST.ModKey, true))
                    {
                        applySetToFLST(HearthFireStores_GS.FormList.xHFSxConstructionFLST, hearthFiresConstructionSet);
                        applySetToFLST(HearthFireStores_GS.FormList.xHFSxIngredientsFLST, hearthFiresIngredientSet);
                    }
                    break;
                default:
                    throw new NotImplementedException("");
            }
        }
    }
}
